name: Run Tests CI

on: 
  workflow_dispatch: 
  push:
    branches:
      - main

jobs: 
  build-deploy: 
    runs-on: "ubuntu-latest"

    steps: 
      - name : Checkout Code
        uses : actions/checkout@v3

      - name : Setup Node
        uses : actions/setup-node@v3
        with : 
          node-version: 20
          cache: 'npm'

      - name : Install Dependencies
        run  : npm install

      # start server for integration testing
      - name : Start Server in Background
        run  : npm start &

      - name : Wait for Server and Run Tests
        run  : |
            npx wait-on http://localhost:3000 --timeout 60000
            npm run test 
